### ISSUE TITLE
Flip through pictures and download files

### ISSUE THREAD

**Issue by Ararva** [ACLzz/Rule34-Universal-Android-Client#1]
Hello. The application is very interesting and I would like you to develop it further, but it is still not convenient enough. How about flipping through pictures? I could not flip through the images with a swipe, only tap on the edges. And without this it is not very convenient
Also, some pictures do not open - big white "x"
It is also worth adding download and favorites buttons. There is a very lack of these functions. I will follow

**Comment by ACLzz** [comment]
I appreciate that you are interested in my app) Thx for proposals, I would add "favorites" tab and picture download in a short time.

>Also, some pictures do not open - big white "x"
It's cause app still can't load videos, but I will fix it too

Swipes are good idea. I will replace details fragment with pager widget and it will looks better
